### ISSUE TITLE
Fix for Bulgaria (moving to next Monday, Christmas & Easter)

### ISSUE THREAD

**Issue by stefanov-sm** [christopherthompson81/pgsql_holidays#2]
Very useful and impressive. Congrats!
Here are a few corrections for my home country.

```
-- helper function
-- move a holiday to next monday if necessary
CREATE OR REPLACE FUNCTION holidays.bg_fix(d date) 
 RETURNS date 
 LANGUAGE sql IMMUTABLE
AS $function$
 select case when extract(DOW from d)::integer in (6, 0) then holidays.find_nth_weekday_date(d, 1, 1) else d end;
$function$;

CREATE OR REPLACE FUNCTION holidays.bulgaria(p_start_year integer, p_end_year integer)
 RETURNS SETOF holidays.holiday
 LANGUAGE plpgsql
AS $function$

DECLARE
	-- Month Constants
	JANUARY INTEGER := 1;
	FEBRUARY INTEGER := 2;
	MARCH INTEGER := 3;
	APRIL INTEGER := 4;
	MAY INTEGER := 5;
	JUNE INTEGER := 6;
	JULY INTEGER := 7;
	AUGUST INTEGER := 8;
	SEPTEMBER INTEGER := 9;
	OCTOBER INTEGER := 10;
	NOVEMBER INTEGER := 11;
	DECEMBER INTEGER := 12;
	-- Weekday Constants
	SUNDAY INTEGER := 0;
	MONDAY INTEGER := 1;
	TUESDAY INTEGER := 2;
	WEDNESDAY INTEGER := 3;
	THURSDAY INTEGER := 4;
	FRIDAY INTEGER := 5;
	SATURDAY INTEGER := 6;
	WEEKEND INTEGER[] := ARRAY[0, 6];
	-- Primary Loop
	t_years INTEGER[] := (SELECT ARRAY(SELECT generate_series(p_start_year, p_end_year)));
	-- Holding Variables
	t_year INTEGER;
	t_datestamp DATE;
	christmas_start DATE;
	christmas_offsets integer[];
	christmas_offset integer;
	t_holiday holidays.holiday%rowtype;

BEGIN
	FOREACH t_year IN ARRAY t_years
	LOOP
		-- Return an empty list prior to the current country existing
		IF t_year < 1990 THEN
			RETURN;
		END IF;

		-- New Year's Day
		t_holiday.datestamp :=  holidays.bg_fix(make_date(t_year, JANUARY, 1));
		t_holiday.description := 'Нова година';
		RETURN NEXT t_holiday;

		-- Liberation Day
		t_holiday.datestamp :=  holidays.bg_fix(make_date(t_year, MARCH, 3));
		t_holiday.description := 'Ден на Освобождението на България от османско иго';
		RETURN NEXT t_holiday;

		-- International Workers' Day
		t_holiday.datestamp :=  holidays.bg_fix(make_date(t_year, MAY, 1));
		t_holiday.description := 'Ден на труда и на международната работническа солидарност';
		RETURN NEXT t_holiday;

		-- Saint George's Day
		t_holiday.datestamp :=  holidays.bg_fix(make_date(t_year, MAY, 6));
		t_holiday.description := 'Гергьовден, Ден на храбростта и Българската армия';
		RETURN NEXT t_holiday;

		-- Bulgarian Education and Culture and Slavonic Literature Day
		t_holiday.datestamp :=  holidays.bg_fix(make_date(t_year, MAY, 24));
		t_holiday.description := 'Ден на българската просвета и култура и на славянската писменост';
		RETURN NEXT t_holiday;

		-- Unification Day
		t_holiday.datestamp :=  holidays.bg_fix(make_date(t_year, SEPTEMBER, 6));
		t_holiday.description := 'Ден на Съединението';
		RETURN NEXT t_holiday;

		-- Independence Day
		t_holiday.datestamp :=  holidays.bg_fix(make_date(t_year, SEPTEMBER, 22));
		t_holiday.description := 'Ден на Независимостта на България';
		RETURN NEXT t_holiday;

		-- National Awakening Day - but still a business day
		-- t_holiday.datestamp :=  holidays.bg_fix(make_date(t_year, NOVEMBER, 1));
		-- t_holiday.description := 'Ден на народните будители';
		-- RETURN NEXT t_holiday;

		-- Christmas
		christmas_start := make_date(t_year, DECEMBER, 24);
		christmas_offsets := case extract(DOW from christmas_start)::integer
			when THURSDAY then array[0, 1, 4]  -- thursday -> thursday, friday, monday
			when FRIDAY then array[0, 3, 4]  -- friday   -> friday, monday, tuesday
			when SATURDAY then array[2, 3, 4]  -- saturday -> monday, tuesday, wednesday
			when SUNDAY then array[1, 2, 3]  -- sunday   -> monday, tuesday, wednesday
			else array[0, 1, 2] end;
		foreach christmas_offset in array christmas_offsets loop
			t_holiday.description := 'Рождество Христово';
			t_holiday.datestamp := christmas_start + christmas_offset;
			RETURN NEXT t_holiday;
		end loop;
			
		-- Easter
		t_datestamp := holidays.easter(t_year, p_method => 'EASTER_ORTHODOX');
		t_holiday.datestamp := t_datestamp - '2 Days'::INTERVAL;
		t_holiday.description := 'Разпети петък';
		RETURN NEXT t_holiday;
		t_holiday.datestamp := t_datestamp + '1 Days'::INTERVAL;
		t_holiday.description := 'Велики понеделник';
		RETURN NEXT t_holiday;

	END LOOP;
END;

$function$;
```

**Comment by christopherthompson81** [comment]
Thank you for the feedback! I'll try to make a fix shortly. I'm also able to review pull requests to patch the package.

**Comment by christopherthompson81** [comment]
Since I'm naively porting the code from python, it's hard for me to know if it was implemented correctly upstream. Date shifting wasn't implemented in the python lib for Bulgaria, so thank-you for letting me know that it should be there.

I've made some changes to a new branch of the code ("complex_return_experiment"). I'm looking into a more complex return type so that it would be easier to filter data on parameters that aren't directly knowable from the datestamp. This is partially how I want to address your issue. Could you look at the output below and let me know if it would better suit what you would need?

| datestamp  | description | authority | day_off | observation_shifted |
| ---------- | ----------- | --------- | ------- | ------------------- |
| 2020-01-01 | Нова година | national | true | false |
| 2020-03-03 | Ден на Освобождението на България от османско иго | national | true | false |
| 2020-04-17 | Велики петък | national | true | false |
| 2020-04-18 | Велика събота | religious | false | false |
| 2020-04-19 | Великден | religious | false | false |
| 2020-04-20 | Велики понеделник | national | true | false |
| 2020-05-01 | Ден на труда и на международната работническа солидарност | national | true | false |
| 2020-05-06 | Гергьовден, Ден на храбростта и Българската армия | national | true | false |
| 2020-05-24 | Ден на българската просвета и култура и на славянската писменост | national | true | false |
| 2020-05-25 | Ден на българската просвета и култура и на славянската писменост (Observed) | national | true | true |
| 2020-09-06 | Ден на Съединението | national | true | false |
| 2020-09-07 | Ден на Съединението (Observed) | national | true | true |
| 2020-09-22 | Ден на Независимостта на България | national | true | false |
| 2020-11-01 | Ден на народните будители | national | false | false |
| 2020-12-24 | Бъдни вечер | national | true | false |
| 2020-12-25 | Рождество Христово | national | true | false |
| 2020-12-28 | Рождество Христово | national | true | true |

I'm not fully sure if I should drop the English "(Observed)" tags if I use this format, so I'd be curious about your thoughts on that too.

**Comment by stefanov-sm** [comment]
I think that the new return format is excellent and suites both business use and general information cases. 

About the English "(Observed)" tags - well, it's good to have of course. 
What about declaring something like
`OBSERVED constant text := '(компенсация)'; -- Bulgarian `
in country functions and then use the constant instead of the literal?

One more thought. Holiday lists and rules are changed every now and then in countries around the world and this may go unnoticed. Maybe local people are the best opportunity for updating. 
A more declarative approach could help them do so, something like this HOLIDAY_DEFINITIONS "table" in country functions.
```
create type holidays.holiday_def as
(
 month_value integer,
 day_value integer,
 description text,
 day_off boolean,
 authority holidays.jurisdictional_authority,
 observation_shift boolean
);

-- declare
HOLIDAY_DEFINITIONS constant holidays.holiday_def[] := array
[
-- MONTH_VALUE DAY_VALUE  DESCRIPTION                     OFF_DAY AUTHORITY   SHIFT
   (JANUARY,           1, 'Нова година',                  true,   'national', true),
   (MARCH,             3, 'Освобождение от османско иго', true,   'national', true),
   (MAY,               1, 'Ден на труда',                 true,   'national', true),
   (MAY,               6, 'Гергьовден',                   true,   'national', true),
   (MAY,              24, 'Ден на писмеността',           true,   'national', true),
   (SEPTEMBER,         6, 'Ден на Съединението',          true,   'national', true),
   (SEPTEMBER,        22, 'Ден на Независимостта',        true,   'national', true),
   (NOVEMBER,          1, 'Ден на народните будители',    false,  'national', false)
];
running_holiday holidays.holiday_def;

-- begin 
foreach running_holiday in array HOLIDAY_DEFINITIONS loop
	-- generic country-independent business logic here 
end loop;
```
Cheers!
